"""initial_tables

Revision ID: 6f7b369c6aef
Revises: 
Create Date: 2026-05-25 18:43:41.027610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7b369c6aef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('daily_max_slots', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('nid_hash', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_nid_hash'), 'patients', ['nid_hash'], unique=True)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=False),
    sa.Column('appt_date', sa.Date(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'ATTENDED', name='appointmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_id', 'appt_date', 'serial_no', name='uq_dept_date_serial'),
    sa.UniqueConstraint('patient_id', 'appt_date', name='uq_patient_date')
    )
    op.create_index(op.f('ix_appointments_appt_date'), 'appointments', ['appt_date'], unique=False)
    op.create_index(op.f('ix_appointments_dept_id'), 'appointments', ['dept_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('dept_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_id', 'day_of_week', name='uq_dept_day')
    )
    op.create_table('staff_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'RECEPTIONIST', 'DEPT_MANAGER', 'FINANCE', name='staffrole'), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appt_id', sa.UUID(), nullable=False),
    sa.Column('bkash_trx_id', sa.String(length=50), nullable=True),
    sa.Column('amount_bdt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('bkash_response', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appt_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appt_id'),
    sa.UniqueConstraint('bkash_trx_id')
    )
    op.create_table('qr_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appt_id', sa.UUID(), nullable=False),
    sa.Column('token_hmac', sa.String(length=256), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appt_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_tokens')
    op.drop_table('payments')
    op.drop_table('staff_members')
    op.drop_table('dept_schedules')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_dept_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appt_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_nid_hash'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('departments')
    # ### end Alembic commands ###